### ISSUE TITLE
Optional: Scale bezier handle point coordinates 

### ISSUE THREAD

**Issue by Dsrenger** [Marc-Frank/BezierAirfoilDesigner#1]
As discussed in RCN scaling the bezier spline in the CAD system may be a little bit tricky. Depending on the CAD system.

Therefore it would be nice to be able to scale the X and Y coordinates of the bezier handlers to a profile depth given by the user. Of course this should be optional.

This would result in a correctly scaled profile in CAD without manually calculating or changing the handler coordinates.

Thanks for this great tool :)

**Comment by marc-frank** [comment]
Just added this feature to the code. The scaling is only applied during export.
Will be available in the next release.
