### ISSUE TITLE
Behavior when pressing "stop"

### ISSUE THREAD

**Issue by Dsrenger** [Marc-Frank/BezierAirfoilDesigner#2]
When I understand it correctly, the tool tries different handler point coordinates and "saves" the best ones (behind the scenes) while trying others to be sure there are no better coordinates until it tried every combination for this order.

Then it jumps to the best coordinates he found and increases the order and starts over again.

I had a profile, that took very ong to analyse.

After a couple of hours I pressed "stop" and I think the tool did just stop at the coordinates he just checked.

I think it would make sense, that the tool will jump to the "best" coordinates he found during the process  when you press stop.
Think there are saved somewhere, right?

I might be completly wrong with my conclussions, but I think, when I pressed stop, I didnt had the best curve he found during the process, right?

**Comment by marc-frank** [comment]
Hi, yes the exiting of the search function was done sligthly wrong.
Should be fixed in the next release.
