### ISSUE TITLE
DAT export with X/Y/Z coordinates

### ISSUE THREAD

**Issue by hommelm** [Marc-Frank/BezierAirfoilDesigner#3]
In SW a pointcloud only can importet with three axis. Means X/Y/Z.
The exportet DAT file only have the axis X/Y. (which is normal)
Is it possible to generate a DAT export file with X/Y/Z coordinates ? 
In this case the "Z" axis should only have the value "0"

![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/38975897/3207c16d-dcfd-48fd-a389-9459676615f6)

**Comment by marc-frank** [comment]
Do you need special seperation characters, like in a csv?
I'll add a selection box that lets you choose if the x, y or z coordinate should be set to 0.

**Comment by hommelm** [comment]
No, there is no special seperation character needed.
The coordinates are seperatet wicht a "space"

![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/38975897/15260515-c579-4d45-acf2-6732ad2b0d67)

**Comment by marc-frank** [comment]
That's great! Simplifies things a lot.
I now have this:
![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/74321912/c4385408-8aa8-40e3-bfec-af526ab3fe51)
Which produces a file like this:
![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/74321912/fb5cb492-f590-4f1e-ae63-69c4a8502143)
Is a single 0 enough for importing into SolidWorks or do you need 0.000...?

**Comment by hommelm** [comment]
The single "0" is enough.
Thanks a lot, i will try this out.

**Comment by marc-frank** [comment]
New Release is uploaded :)

**Comment by hommelm** [comment]
I calculatetd a bezier profil.
The "0" for "Z" is only for one side in the export file.
![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/38975897/d76cd8ca-f20c-4e7b-baf8-ef04f4d2915c)


If i export the "bez.dat" there is no "0" for "Z"
![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/38975897/f3b8d6ed-71bb-4a51-8f08-6ee3042e7c6a)

**Comment by marc-frank** [comment]
Both fixed in the next release
