### ISSUE TITLE
Im Bereich der Nasenleiste noch zu ungenau

### ISSUE THREAD

**Issue by DirkPflug** [Marc-Frank/BezierAirfoilDesigner#4]
Hi Marc,

zunächst mal ein großes Kompliment an Dich: der BezierAirfoilDesigner ist ein super Tool was genau in die richtige Lücke zielt. Auch sehr einfach gestaltet. Das muß man erst mal so hinkriegen. Bravo!

Zwischenzeitlich habe ich es ausprobiert und die Ergebnisse kontrolliert. Was mir auffällt ist, dass die Kurven im Bereich der Nasenleiste noch nicht optimal sind. Hier solltest Du unbedingt nochmals nachschauen ob man das besser hinkriegt. Sollte dieses dann auch passen, dann ist es wirklich super! Toll wäre es auch, wenn Du die Schwarmoptimierung implementieren kannst um die Bearbeitungszeit und CPU-Belastung zu reduzieren.

Vielen Dank für Deine Mühe!

Dirk Pflug

**Comment by marc-frank** [comment]
Moin Dirk,

vielen Dank :)

Ich habe die Berechnung des Errors jetzt angepasst, sodass die Verteilung der X-Positionen an denen der Unterschied zum Referenzprofil berechnet wird nicht mehr gleichmäßig ist, sondern auch nach Sinus oder Cosinus verteilt werden kann.

![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/74321912/2c91dc5f-69fb-48cd-81c7-b69ca7741e29)
https://www.geogebra.org/calculator/q27mqzbg

Hier ist das Ergebnis von einer Anpassung, bei der der Error mit Cosinus-Verteilung berechnet wurde:

![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/74321912/36164e02-750e-413a-be0a-6de0b79e7bde)

Und hier wie es vorher war:

![image](https://github.com/Marc-Frank/BezierAirfoilDesigner/assets/74321912/494e6b76-067f-4a23-92cf-5e80d471adcb)

Es sieht so aus, als wäre es ein bisschen besser geworden.
Viel hat sich da aber nicht getan. Vielleicht ist es bei anderen Profilen besser?
Man könnte  es nochmal mit Sinus ausprobieren, das müsste die Nasenleiste noch stärker gewichten.
Sonst habe ich nicht wirklich eine Idee, wie man die Wichtigkeit der Anpassung an die Nasenleiste erhöhen kann.

Vielleicht funktioniert es mit der Schwarmoptimierung besser, das zu implementieren wird aber wohl etwas länger dauern.

**Comment by DirkPflug** [comment]
Super, werde das gleich mal ausprobieren wenn Du die neue Version zum download reingestellt hast. Danke!

**Comment by DirkPflug** [comment]
Ist es vielleicht möglich eine Funktion zu integrieren, mit der die **roten** Punkte manuell an die Originaldaten angepasst werden können?

**Comment by marc-frank** [comment]
Moin Dirk, die neue Version ist jetzt hochgeladen :)

Bezier Kurven rückwärts auszurechnen ist nicht wirklich leicht.
Bei 3 Kontrollpunkten geht es noch gerade so, man muss nur den t-Wert von dem Punkt schätzen.
Wenn man einen Punkt auf der Kurve verschiebt von dem man t schon kennt geht es ganz gut.
Das ändert sich aber schnell mit mehr als 3 Kontrollpunkten. Dann gibt es (fast) unendlich viele Lösungen für die Positionen der Kontrollpunkte. Jeder beeinflusst ja den Verlauf der gesamten Kurve.

Hier hatte ich das mal in Excel ausprobiert:
[Bézier Curves.xlsx](https://github.com/Marc-Frank/BezierAirfoilDesigner/files/12299249/Bezier.Curves.xlsx)

**Comment by marc-frank** [comment]
Moin Dirk,

habe jetzt die Partikelschwarmoptimierung hinzugefügt.
Das ist sehr viel schneller, als die bisherige Suchmethode.
Die kann man aber immer noch benutzen,
um einen guten Startpunkt für die PSO zu bekommen.

Ich glaube damit kann man den Issue schließen.
Wenn du neue Vorschläge hast oder dir Fehler auffallen,
bitte wieder schreiben.

Grüße,
Marc
